/*
 * This file is generated by jOOQ.
 */
package com.huice.service_dyna.db.tables;


import com.huice.service_dyna.db.FdkForwarder2;
import com.huice.service_dyna.db.Indexes;
import com.huice.service_dyna.db.Keys;
import com.huice.service_dyna.db.tables.records.SellerRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 销售商表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Seller extends TableImpl<SellerRecord> {

    private static final long serialVersionUID = -1906319096;

    /**
     * The reference instance of <code>fdk_forwarder2.seller</code>
     */
    public static final Seller SELLER = new Seller();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SellerRecord> getRecordType() {
        return SellerRecord.class;
    }

    /**
     * The column <code>fdk_forwarder2.seller.id</code>.
     */
    public final TableField<SellerRecord, ULong> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "");

    /**
     * The column <code>fdk_forwarder2.seller.platform_code</code>. 销售商来源平台|@0：发得快|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, String> PLATFORM_CODE = createField(DSL.name("platform_code"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销售商来源平台|@0：发得快|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.platform_identity</code>. 销售商所在平台唯一身份ID|@发得快：merchantId；|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, ULong> PLATFORM_IDENTITY = createField(DSL.name("platform_identity"), org.jooq.impl.SQLDataType.BIGINTUNSIGNED.nullable(false), this, "销售商所在平台唯一身份ID|@发得快：merchantId；|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.name</code>. 销售商名称|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, String> NAME = createField(DSL.name("name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销售商名称|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.short_name</code>. 销售商简称|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, String> SHORT_NAME = createField(DSL.name("short_name"), org.jooq.impl.SQLDataType.VARCHAR(50).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "销售商简称|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.user_name</code>. 联系人姓名|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, String> USER_NAME = createField(DSL.name("user_name"), org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "联系人姓名|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.user_phone</code>. 联系人手机号|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, String> USER_PHONE = createField(DSL.name("user_phone"), org.jooq.impl.SQLDataType.VARCHAR(13).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "联系人手机号|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.province</code>. 省|wendiyou|2021-6-28
     */
    public final TableField<SellerRecord, Integer> PROVINCE = createField(DSL.name("province"), org.jooq.impl.SQLDataType.INTEGER, this, "省|wendiyou|2021-6-28");

    /**
     * The column <code>fdk_forwarder2.seller.city</code>. 市|wendiyou|2021-6-28
     */
    public final TableField<SellerRecord, Integer> CITY = createField(DSL.name("city"), org.jooq.impl.SQLDataType.INTEGER, this, "市|wendiyou|2021-6-28");

    /**
     * The column <code>fdk_forwarder2.seller.district</code>. 区|wendiyou|2021-6-28
     */
    public final TableField<SellerRecord, Integer> DISTRICT = createField(DSL.name("district"), org.jooq.impl.SQLDataType.INTEGER, this, "区|wendiyou|2021-6-28");

    /**
     * The column <code>fdk_forwarder2.seller.area</code>. 省市区名称|wendiyou|2021-6-28
     */
    public final TableField<SellerRecord, String> AREA = createField(DSL.name("area"), org.jooq.impl.SQLDataType.VARCHAR(255).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "省市区名称|wendiyou|2021-6-28");

    /**
     * The column <code>fdk_forwarder2.seller.address</code>. 详细地址|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, String> ADDRESS = createField(DSL.name("address"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "详细地址|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.status</code>. 状态|@0:默认值、有效；@1：已删除状态；|wendiyou|2021-06-07
     */
    public final TableField<SellerRecord, UByte> STATUS = createField(DSL.name("status"), org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "状态|@0:默认值、有效；@1：已删除状态；|wendiyou|2021-06-07");

    /**
     * The column <code>fdk_forwarder2.seller.created</code>.
     */
    public final TableField<SellerRecord, Timestamp> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>fdk_forwarder2.seller.modified</code>.
     */
    public final TableField<SellerRecord, Timestamp> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>fdk_forwarder2.seller</code> table reference
     */
    public Seller() {
        this(DSL.name("seller"), null);
    }

    /**
     * Create an aliased <code>fdk_forwarder2.seller</code> table reference
     */
    public Seller(String alias) {
        this(DSL.name(alias), SELLER);
    }

    /**
     * Create an aliased <code>fdk_forwarder2.seller</code> table reference
     */
    public Seller(Name alias) {
        this(alias, SELLER);
    }

    private Seller(Name alias, Table<SellerRecord> aliased) {
        this(alias, aliased, null);
    }

    private Seller(Name alias, Table<SellerRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("销售商表"));
    }

    public <O extends Record> Seller(Table<O> child, ForeignKey<O, SellerRecord> key) {
        super(child, key, SELLER);
    }

    @Override
    public Schema getSchema() {
        return FdkForwarder2.FDK_FORWARDER2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.SELLER_PLATFORM_CODE, Indexes.SELLER_PRIMARY, Indexes.SELLER_SHORT_NAME);
    }

    @Override
    public UniqueKey<SellerRecord> getPrimaryKey() {
        return Keys.KEY_SELLER_PRIMARY;
    }

    @Override
    public List<UniqueKey<SellerRecord>> getKeys() {
        return Arrays.<UniqueKey<SellerRecord>>asList(Keys.KEY_SELLER_PRIMARY, Keys.KEY_SELLER_PLATFORM_CODE, Keys.KEY_SELLER_SHORT_NAME);
    }

    @Override
    public Seller as(String alias) {
        return new Seller(DSL.name(alias), this);
    }

    @Override
    public Seller as(Name alias) {
        return new Seller(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Seller rename(String name) {
        return new Seller(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Seller rename(Name name) {
        return new Seller(name, null);
    }

    // -------------------------------------------------------------------------
    // Row15 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row15<ULong, String, ULong, String, String, String, String, Integer, Integer, Integer, String, String, UByte, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }
}
