server:
  port: 8082

spring:
  application:
    name: fdk-service
  datasource:
    url: jdbc:mysql://60.205.180.234:3306/fdk_goods2?serverTimezone=Asia/Shanghai
    username: fdk_summer2
    password: lahmyyc123
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: hc-summer-2
      config:
        server-addr: http://localhost:8848
        encode: UTF-8
        namespace: hc-summer-2

