server:
  port: 8082

spring:
  application:
    name: fdk_service
  datasource:
    url: jdbc:mysql://60.205.180.234:3306/fdk_goods2?serverTimezone=Asia/Shanghai
    username: fdk_summer2
    password: lahmyyc123
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: f97a8269-e181-4c34-8be0-dbffed18ded0
      config:
        server-addr: http://localhost:8848
        encode: UTF-8
        namespace: f97a8269-e181-4c34-8be0-dbffed18ded0

