server:
  port: 8082

spring:
  application:
    name: fdk-user
  cloud:
    nacos:
      discovery:
        server-addr: http://121.4.191.125:8848
        namespace: f97a8269-e181-4c34-8be0-dbffed18ded0
        username: nacos
        password: nacos
  datasource:
    url: jdbc:mysql://60.205.180.234:3306/fdk_goods2?serverTimezone=Asia/Shanghai
    username: fdk
    password: fdksu123456