/*
 * This file is generated by jOOQ.
 */
package com.huice.service_dyna.db.tables.records;


import com.huice.service_dyna.db.tables.PlatformSpu;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 系统货品|郑保乐|2021-06-08
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlatformSpuRecord extends UpdatableRecordImpl<PlatformSpuRecord> implements Record12<Long, Long, Long, Long, Long, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp> {

    private static final long serialVersionUID = 726883884;

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.id</code>. id|郑保乐|2021-06-08
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.id</code>. id|郑保乐|2021-06-08
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.city_id</code>. 城市id|郑保乐|2021-06-08
     */
    public void setCityId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.city_id</code>. 城市id|郑保乐|2021-06-08
     */
    public Long getCityId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.market_id</code>. 市场id|郑保乐|2021-06-08
     */
    public void setMarketId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.market_id</code>. 市场id|郑保乐|2021-06-08
     */
    public Long getMarketId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.floor_code</code>. 楼层编码（int）|郑保乐|2021-06-08
     */
    public void setFloorCode(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.floor_code</code>. 楼层编码（int）|郑保乐|2021-06-08
     */
    public Long getFloorCode() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.biz_id</code>. 档口表id|郑保乐|2021-06-08
     */
    public void setBizId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.biz_id</code>. 档口表id|郑保乐|2021-06-08
     */
    public Long getBizId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.spu_name</code>. SPU名称|郑保乐|2021-06-08
     */
    public void setSpuName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.spu_name</code>. SPU名称|郑保乐|2021-06-08
     */
    public String getSpuName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.main_img_url</code>. 图片URL|郑保乐|2021-06-08
     */
    public void setMainImgUrl(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.main_img_url</code>. 图片URL|郑保乐|2021-06-08
     */
    public String getMainImgUrl() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.spu_goods_no</code>. 货号|郑保乐|2021-06-08
     */
    public void setSpuGoodsNo(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.spu_goods_no</code>. 货号|郑保乐|2021-06-08
     */
    public String getSpuGoodsNo() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.total_fetch</code>. 总已拿货结账数量|郑保乐|2021-06-08
     */
    public void setTotalFetch(BigDecimal value) {
        set(8, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.total_fetch</code>. 总已拿货结账数量|郑保乐|2021-06-08
     */
    public BigDecimal getTotalFetch() {
        return (BigDecimal) get(8);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.total_return</code>. 总已退货结账数量|郑保乐|2021-06-08
     */
    public void setTotalReturn(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.total_return</code>. 总已退货结账数量|郑保乐|2021-06-08
     */
    public BigDecimal getTotalReturn() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>fdk_forwarder2.platform_spu.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.platform_spu.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, Long, Long, Long, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    @Override
    public Row12<Long, Long, Long, Long, Long, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return PlatformSpu.PLATFORM_SPU.ID;
    }

    @Override
    public Field<Long> field2() {
        return PlatformSpu.PLATFORM_SPU.CITY_ID;
    }

    @Override
    public Field<Long> field3() {
        return PlatformSpu.PLATFORM_SPU.MARKET_ID;
    }

    @Override
    public Field<Long> field4() {
        return PlatformSpu.PLATFORM_SPU.FLOOR_CODE;
    }

    @Override
    public Field<Long> field5() {
        return PlatformSpu.PLATFORM_SPU.BIZ_ID;
    }

    @Override
    public Field<String> field6() {
        return PlatformSpu.PLATFORM_SPU.SPU_NAME;
    }

    @Override
    public Field<String> field7() {
        return PlatformSpu.PLATFORM_SPU.MAIN_IMG_URL;
    }

    @Override
    public Field<String> field8() {
        return PlatformSpu.PLATFORM_SPU.SPU_GOODS_NO;
    }

    @Override
    public Field<BigDecimal> field9() {
        return PlatformSpu.PLATFORM_SPU.TOTAL_FETCH;
    }

    @Override
    public Field<BigDecimal> field10() {
        return PlatformSpu.PLATFORM_SPU.TOTAL_RETURN;
    }

    @Override
    public Field<Timestamp> field11() {
        return PlatformSpu.PLATFORM_SPU.CREATED;
    }

    @Override
    public Field<Timestamp> field12() {
        return PlatformSpu.PLATFORM_SPU.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCityId();
    }

    @Override
    public Long component3() {
        return getMarketId();
    }

    @Override
    public Long component4() {
        return getFloorCode();
    }

    @Override
    public Long component5() {
        return getBizId();
    }

    @Override
    public String component6() {
        return getSpuName();
    }

    @Override
    public String component7() {
        return getMainImgUrl();
    }

    @Override
    public String component8() {
        return getSpuGoodsNo();
    }

    @Override
    public BigDecimal component9() {
        return getTotalFetch();
    }

    @Override
    public BigDecimal component10() {
        return getTotalReturn();
    }

    @Override
    public Timestamp component11() {
        return getCreated();
    }

    @Override
    public Timestamp component12() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCityId();
    }

    @Override
    public Long value3() {
        return getMarketId();
    }

    @Override
    public Long value4() {
        return getFloorCode();
    }

    @Override
    public Long value5() {
        return getBizId();
    }

    @Override
    public String value6() {
        return getSpuName();
    }

    @Override
    public String value7() {
        return getMainImgUrl();
    }

    @Override
    public String value8() {
        return getSpuGoodsNo();
    }

    @Override
    public BigDecimal value9() {
        return getTotalFetch();
    }

    @Override
    public BigDecimal value10() {
        return getTotalReturn();
    }

    @Override
    public Timestamp value11() {
        return getCreated();
    }

    @Override
    public Timestamp value12() {
        return getModified();
    }

    @Override
    public PlatformSpuRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value2(Long value) {
        setCityId(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value3(Long value) {
        setMarketId(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value4(Long value) {
        setFloorCode(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value5(Long value) {
        setBizId(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value6(String value) {
        setSpuName(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value7(String value) {
        setMainImgUrl(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value8(String value) {
        setSpuGoodsNo(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value9(BigDecimal value) {
        setTotalFetch(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value10(BigDecimal value) {
        setTotalReturn(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value11(Timestamp value) {
        setCreated(value);
        return this;
    }

    @Override
    public PlatformSpuRecord value12(Timestamp value) {
        setModified(value);
        return this;
    }

    @Override
    public PlatformSpuRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, String value6, String value7, String value8, BigDecimal value9, BigDecimal value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlatformSpuRecord
     */
    public PlatformSpuRecord() {
        super(PlatformSpu.PLATFORM_SPU);
    }

    /**
     * Create a detached, initialised PlatformSpuRecord
     */
    public PlatformSpuRecord(Long id, Long cityId, Long marketId, Long floorCode, Long bizId, String spuName, String mainImgUrl, String spuGoodsNo, BigDecimal totalFetch, BigDecimal totalReturn, Timestamp created, Timestamp modified) {
        super(PlatformSpu.PLATFORM_SPU);

        set(0, id);
        set(1, cityId);
        set(2, marketId);
        set(3, floorCode);
        set(4, bizId);
        set(5, spuName);
        set(6, mainImgUrl);
        set(7, spuGoodsNo);
        set(8, totalFetch);
        set(9, totalReturn);
        set(10, created);
        set(11, modified);
    }
}
