/*
 * This file is generated by jOOQ.
 */
package com.huice.service_dyna.db.tables.records;


import com.huice.service_dyna.db.tables.Seller;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record15;
import org.jooq.Row15;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.ULong;


/**
 * 销售商表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SellerRecord extends UpdatableRecordImpl<SellerRecord> implements Record15<ULong, String, ULong, String, String, String, String, Integer, Integer, Integer, String, String, UByte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 75276771;

    /**
     * Setter for <code>fdk_forwarder2.seller.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.platform_code</code>. 销售商来源平台|@0：发得快|wendiyou|2021-06-07
     */
    public void setPlatformCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.platform_code</code>. 销售商来源平台|@0：发得快|wendiyou|2021-06-07
     */
    public String getPlatformCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.platform_identity</code>. 销售商所在平台唯一身份ID|@发得快：merchantId；|wendiyou|2021-06-07
     */
    public void setPlatformIdentity(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.platform_identity</code>. 销售商所在平台唯一身份ID|@发得快：merchantId；|wendiyou|2021-06-07
     */
    public ULong getPlatformIdentity() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.name</code>. 销售商名称|wendiyou|2021-06-07
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.name</code>. 销售商名称|wendiyou|2021-06-07
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.short_name</code>. 销售商简称|wendiyou|2021-06-07
     */
    public void setShortName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.short_name</code>. 销售商简称|wendiyou|2021-06-07
     */
    public String getShortName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.user_name</code>. 联系人姓名|wendiyou|2021-06-07
     */
    public void setUserName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.user_name</code>. 联系人姓名|wendiyou|2021-06-07
     */
    public String getUserName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.user_phone</code>. 联系人手机号|wendiyou|2021-06-07
     */
    public void setUserPhone(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.user_phone</code>. 联系人手机号|wendiyou|2021-06-07
     */
    public String getUserPhone() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.province</code>. 省|wendiyou|2021-6-28
     */
    public void setProvince(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.province</code>. 省|wendiyou|2021-6-28
     */
    public Integer getProvince() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.city</code>. 市|wendiyou|2021-6-28
     */
    public void setCity(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.city</code>. 市|wendiyou|2021-6-28
     */
    public Integer getCity() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.district</code>. 区|wendiyou|2021-6-28
     */
    public void setDistrict(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.district</code>. 区|wendiyou|2021-6-28
     */
    public Integer getDistrict() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.area</code>. 省市区名称|wendiyou|2021-6-28
     */
    public void setArea(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.area</code>. 省市区名称|wendiyou|2021-6-28
     */
    public String getArea() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.address</code>. 详细地址|wendiyou|2021-06-07
     */
    public void setAddress(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.address</code>. 详细地址|wendiyou|2021-06-07
     */
    public String getAddress() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.status</code>. 状态|@0:默认值、有效；@1：已删除状态；|wendiyou|2021-06-07
     */
    public void setStatus(UByte value) {
        set(12, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.status</code>. 状态|@0:默认值、有效；@1：已删除状态；|wendiyou|2021-06-07
     */
    public UByte getStatus() {
        return (UByte) get(12);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(13, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(13);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record15 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row15<ULong, String, ULong, String, String, String, String, Integer, Integer, Integer, String, String, UByte, Timestamp, Timestamp> fieldsRow() {
        return (Row15) super.fieldsRow();
    }

    @Override
    public Row15<ULong, String, ULong, String, String, String, String, Integer, Integer, Integer, String, String, UByte, Timestamp, Timestamp> valuesRow() {
        return (Row15) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return Seller.SELLER.ID;
    }

    @Override
    public Field<String> field2() {
        return Seller.SELLER.PLATFORM_CODE;
    }

    @Override
    public Field<ULong> field3() {
        return Seller.SELLER.PLATFORM_IDENTITY;
    }

    @Override
    public Field<String> field4() {
        return Seller.SELLER.NAME;
    }

    @Override
    public Field<String> field5() {
        return Seller.SELLER.SHORT_NAME;
    }

    @Override
    public Field<String> field6() {
        return Seller.SELLER.USER_NAME;
    }

    @Override
    public Field<String> field7() {
        return Seller.SELLER.USER_PHONE;
    }

    @Override
    public Field<Integer> field8() {
        return Seller.SELLER.PROVINCE;
    }

    @Override
    public Field<Integer> field9() {
        return Seller.SELLER.CITY;
    }

    @Override
    public Field<Integer> field10() {
        return Seller.SELLER.DISTRICT;
    }

    @Override
    public Field<String> field11() {
        return Seller.SELLER.AREA;
    }

    @Override
    public Field<String> field12() {
        return Seller.SELLER.ADDRESS;
    }

    @Override
    public Field<UByte> field13() {
        return Seller.SELLER.STATUS;
    }

    @Override
    public Field<Timestamp> field14() {
        return Seller.SELLER.CREATED;
    }

    @Override
    public Field<Timestamp> field15() {
        return Seller.SELLER.MODIFIED;
    }

    @Override
    public ULong component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getPlatformCode();
    }

    @Override
    public ULong component3() {
        return getPlatformIdentity();
    }

    @Override
    public String component4() {
        return getName();
    }

    @Override
    public String component5() {
        return getShortName();
    }

    @Override
    public String component6() {
        return getUserName();
    }

    @Override
    public String component7() {
        return getUserPhone();
    }

    @Override
    public Integer component8() {
        return getProvince();
    }

    @Override
    public Integer component9() {
        return getCity();
    }

    @Override
    public Integer component10() {
        return getDistrict();
    }

    @Override
    public String component11() {
        return getArea();
    }

    @Override
    public String component12() {
        return getAddress();
    }

    @Override
    public UByte component13() {
        return getStatus();
    }

    @Override
    public Timestamp component14() {
        return getCreated();
    }

    @Override
    public Timestamp component15() {
        return getModified();
    }

    @Override
    public ULong value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getPlatformCode();
    }

    @Override
    public ULong value3() {
        return getPlatformIdentity();
    }

    @Override
    public String value4() {
        return getName();
    }

    @Override
    public String value5() {
        return getShortName();
    }

    @Override
    public String value6() {
        return getUserName();
    }

    @Override
    public String value7() {
        return getUserPhone();
    }

    @Override
    public Integer value8() {
        return getProvince();
    }

    @Override
    public Integer value9() {
        return getCity();
    }

    @Override
    public Integer value10() {
        return getDistrict();
    }

    @Override
    public String value11() {
        return getArea();
    }

    @Override
    public String value12() {
        return getAddress();
    }

    @Override
    public UByte value13() {
        return getStatus();
    }

    @Override
    public Timestamp value14() {
        return getCreated();
    }

    @Override
    public Timestamp value15() {
        return getModified();
    }

    @Override
    public SellerRecord value1(ULong value) {
        setId(value);
        return this;
    }

    @Override
    public SellerRecord value2(String value) {
        setPlatformCode(value);
        return this;
    }

    @Override
    public SellerRecord value3(ULong value) {
        setPlatformIdentity(value);
        return this;
    }

    @Override
    public SellerRecord value4(String value) {
        setName(value);
        return this;
    }

    @Override
    public SellerRecord value5(String value) {
        setShortName(value);
        return this;
    }

    @Override
    public SellerRecord value6(String value) {
        setUserName(value);
        return this;
    }

    @Override
    public SellerRecord value7(String value) {
        setUserPhone(value);
        return this;
    }

    @Override
    public SellerRecord value8(Integer value) {
        setProvince(value);
        return this;
    }

    @Override
    public SellerRecord value9(Integer value) {
        setCity(value);
        return this;
    }

    @Override
    public SellerRecord value10(Integer value) {
        setDistrict(value);
        return this;
    }

    @Override
    public SellerRecord value11(String value) {
        setArea(value);
        return this;
    }

    @Override
    public SellerRecord value12(String value) {
        setAddress(value);
        return this;
    }

    @Override
    public SellerRecord value13(UByte value) {
        setStatus(value);
        return this;
    }

    @Override
    public SellerRecord value14(Timestamp value) {
        setCreated(value);
        return this;
    }

    @Override
    public SellerRecord value15(Timestamp value) {
        setModified(value);
        return this;
    }

    @Override
    public SellerRecord values(ULong value1, String value2, ULong value3, String value4, String value5, String value6, String value7, Integer value8, Integer value9, Integer value10, String value11, String value12, UByte value13, Timestamp value14, Timestamp value15) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SellerRecord
     */
    public SellerRecord() {
        super(Seller.SELLER);
    }

    /**
     * Create a detached, initialised SellerRecord
     */
    public SellerRecord(ULong id, String platformCode, ULong platformIdentity, String name, String shortName, String userName, String userPhone, Integer province, Integer city, Integer district, String area, String address, UByte status, Timestamp created, Timestamp modified) {
        super(Seller.SELLER);

        set(0, id);
        set(1, platformCode);
        set(2, platformIdentity);
        set(3, name);
        set(4, shortName);
        set(5, userName);
        set(6, userPhone);
        set(7, province);
        set(8, city);
        set(9, district);
        set(10, area);
        set(11, address);
        set(12, status);
        set(13, created);
        set(14, modified);
    }
}
