/*
 * This file is generated by jOOQ.
 */
package com.huice.service_dyna.db.tables.records;


import com.huice.service_dyna.db.tables.SellerFetchOrder;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 代拿子单，对应销端小标签|郑保乐|2021-06-08
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SellerFetchOrderRecord extends UpdatableRecordImpl<SellerFetchOrderRecord> {

    private static final long serialVersionUID = 784041438;

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.id</code>. id|郑保乐|2021-06-08
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.id</code>. id|郑保乐|2021-06-08
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.merchant_id</code>. 商户id|郑保乐|2021-06-08
     */
    public void setMerchantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.merchant_id</code>. 商户id|郑保乐|2021-06-08
     */
    public Long getMerchantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.city_id</code>. 城市id|郑保乐|2021-06-08
     */
    public void setCityId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.city_id</code>. 城市id|郑保乐|2021-06-08
     */
    public Long getCityId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.market_id</code>. 市场id|郑保乐|2021-06-08
     */
    public void setMarketId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.market_id</code>. 市场id|郑保乐|2021-06-08
     */
    public Long getMarketId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.floor_code</code>. 楼层编码（int）|郑保乐|2021-06-08
     */
    public void setFloorCode(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.floor_code</code>. 楼层编码（int）|郑保乐|2021-06-08
     */
    public Long getFloorCode() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.biz_id</code>. 档口表id|郑保乐|2021-06-08
     */
    public void setBizId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.biz_id</code>. 档口表id|郑保乐|2021-06-08
     */
    public Long getBizId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.seller_order_id</code>. 销端子单id|郑保乐|2021-06-08
     */
    public void setSellerOrderId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.seller_order_id</code>. 销端子单id|郑保乐|2021-06-08
     */
    public String getSellerOrderId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.platform_spu_id</code>. 平台SPU id|郑保乐|2021-06-08
     */
    public void setPlatformSpuId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.platform_spu_id</code>. 平台SPU id|郑保乐|2021-06-08
     */
    public Long getPlatformSpuId() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.platform_sku_id</code>. 平台SKU id|郑保乐|2021-06-08
     */
    public void setPlatformSkuId(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.platform_sku_id</code>. 平台SKU id|郑保乐|2021-06-08
     */
    public Long getPlatformSkuId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.bill_id</code>. 账单id，未开单为0|郑保乐|2021-06-08
     */
    public void setBillId(Long value) {
        set(9, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.bill_id</code>. 账单id，未开单为0|郑保乐|2021-06-08
     */
    public Long getBillId() {
        return (Long) get(9);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.platform_sku_name</code>. 平台SKU名称|郑保乐|2021-06-08
     */
    public void setPlatformSkuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.platform_sku_name</code>. 平台SKU名称|郑保乐|2021-06-08
     */
    public String getPlatformSkuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.seller_qr_code</code>. 销端二维码|郑保乐|2021-06-08
     */
    public void setSellerQrCode(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.seller_qr_code</code>. 销端二维码|郑保乐|2021-06-08
     */
    public String getSellerQrCode() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.seller_name</code>. 销售商名称|郑保乐|2021-06-21
     */
    public void setSellerName(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.seller_name</code>. 销售商名称|郑保乐|2021-06-21
     */
    public String getSellerName() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.seller_short_name</code>. 销售商简称|郑保乐|2021-06-08
     */
    public void setSellerShortName(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.seller_short_name</code>. 销售商简称|郑保乐|2021-06-08
     */
    public String getSellerShortName() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.platform_barcode</code>. 平台条码|郑保乐|2021-06-08
     */
    public void setPlatformBarcode(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.platform_barcode</code>. 平台条码|郑保乐|2021-06-08
     */
    public String getPlatformBarcode() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.city_name</code>. 城市|郑保乐|2021-06-08
     */
    public void setCityName(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.city_name</code>. 城市|郑保乐|2021-06-08
     */
    public String getCityName() {
        return (String) get(15);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.market_name</code>. 市场|郑保乐|2021-06-08
     */
    public void setMarketName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.market_name</code>. 市场|郑保乐|2021-06-08
     */
    public String getMarketName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.biz_name</code>. 档口|郑保乐|2021-06-08
     */
    public void setBizName(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.biz_name</code>. 档口|郑保乐|2021-06-08
     */
    public String getBizName() {
        return (String) get(17);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.spu_goods_no</code>. 货号|郑保乐|2021-06-08
     */
    public void setSpuGoodsNo(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.spu_goods_no</code>. 货号|郑保乐|2021-06-08
     */
    public String getSpuGoodsNo() {
        return (String) get(18);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.sku_name</code>. SKU名称|郑保乐|2021-06-08
     */
    public void setSkuName(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.sku_name</code>. SKU名称|郑保乐|2021-06-08
     */
    public String getSkuName() {
        return (String) get(19);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.ref_fetch_price</code>. 参考拿货价|郑保乐|2021-06-08
     */
    public void setRefFetchPrice(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.ref_fetch_price</code>. 参考拿货价|郑保乐|2021-06-08
     */
    public BigDecimal getRefFetchPrice() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.real_fetch_price</code>. 实际拿货价|郑保乐|2021-06-08
     */
    public void setRealFetchPrice(BigDecimal value) {
        set(21, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.real_fetch_price</code>. 实际拿货价|郑保乐|2021-06-08
     */
    public BigDecimal getRealFetchPrice() {
        return (BigDecimal) get(21);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.status</code>. 状态：@1拿货中 @2已打印 @3已完结 
     */
    public void setStatus(Byte value) {
        set(22, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.status</code>. 状态：@1拿货中 @2已打印 @3已完结 
     */
    public Byte getStatus() {
        return (Byte) get(22);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.tag_print_flag</code>. 是否已打小标签|郑保乐|2021-06-08
     */
    public void setTagPrintFlag(Byte value) {
        set(23, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.tag_print_flag</code>. 是否已打小标签|郑保乐|2021-06-08
     */
    public Byte getTagPrintFlag() {
        return (Byte) get(23);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.seller_refund_flag</code>. 销端售前退款|郑保乐|2021-06-08
     */
    public void setSellerRefundFlag(Byte value) {
        set(24, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.seller_refund_flag</code>. 销端售前退款|郑保乐|2021-06-08
     */
    public Byte getSellerRefundFlag() {
        return (Byte) get(24);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.scan_time</code>. 扫码到货时间|郑保乐|2021-06-08
     */
    public void setScanTime(Timestamp value) {
        set(25, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.scan_time</code>. 扫码到货时间|郑保乐|2021-06-08
     */
    public Timestamp getScanTime() {
        return (Timestamp) get(25);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.created</code>.
     */
    public void setCreated(Timestamp value) {
        set(26, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.created</code>.
     */
    public Timestamp getCreated() {
        return (Timestamp) get(26);
    }

    /**
     * Setter for <code>fdk_forwarder2.seller_fetch_order.modified</code>.
     */
    public void setModified(Timestamp value) {
        set(27, value);
    }

    /**
     * Getter for <code>fdk_forwarder2.seller_fetch_order.modified</code>.
     */
    public Timestamp getModified() {
        return (Timestamp) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SellerFetchOrderRecord
     */
    public SellerFetchOrderRecord() {
        super(SellerFetchOrder.SELLER_FETCH_ORDER);
    }

    /**
     * Create a detached, initialised SellerFetchOrderRecord
     */
    public SellerFetchOrderRecord(Long id, Long merchantId, Long cityId, Long marketId, Long floorCode, Long bizId, String sellerOrderId, Long platformSpuId, Long platformSkuId, Long billId, String platformSkuName, String sellerQrCode, String sellerName, String sellerShortName, String platformBarcode, String cityName, String marketName, String bizName, String spuGoodsNo, String skuName, BigDecimal refFetchPrice, BigDecimal realFetchPrice, Byte status, Byte tagPrintFlag, Byte sellerRefundFlag, Timestamp scanTime, Timestamp created, Timestamp modified) {
        super(SellerFetchOrder.SELLER_FETCH_ORDER);

        set(0, id);
        set(1, merchantId);
        set(2, cityId);
        set(3, marketId);
        set(4, floorCode);
        set(5, bizId);
        set(6, sellerOrderId);
        set(7, platformSpuId);
        set(8, platformSkuId);
        set(9, billId);
        set(10, platformSkuName);
        set(11, sellerQrCode);
        set(12, sellerName);
        set(13, sellerShortName);
        set(14, platformBarcode);
        set(15, cityName);
        set(16, marketName);
        set(17, bizName);
        set(18, spuGoodsNo);
        set(19, skuName);
        set(20, refFetchPrice);
        set(21, realFetchPrice);
        set(22, status);
        set(23, tagPrintFlag);
        set(24, sellerRefundFlag);
        set(25, scanTime);
        set(26, created);
        set(27, modified);
    }
}
