/*
 * This file is generated by jOOQ.
 */
package com.huice.service_forwarder.db.tables;


import com.huice.service_forwarder.db.FdkForwarder2;
import com.huice.service_forwarder.db.Indexes;
import com.huice.service_forwarder.db.Keys;
import com.huice.service_forwarder.db.tables.records.PlatformSpuRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row12;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * 系统货品|郑保乐|2021-06-08
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlatformSpu extends TableImpl<PlatformSpuRecord> {

    private static final long serialVersionUID = 1532634347;

    /**
     * The reference instance of <code>fdk_forwarder2.platform_spu</code>
     */
    public static final PlatformSpu PLATFORM_SPU = new PlatformSpu();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlatformSpuRecord> getRecordType() {
        return PlatformSpuRecord.class;
    }

    /**
     * The column <code>fdk_forwarder2.platform_spu.id</code>. id|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, Long> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).identity(true), this, "id|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.city_id</code>. 城市id|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, Long> CITY_ID = createField(DSL.name("city_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "城市id|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.market_id</code>. 市场id|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, Long> MARKET_ID = createField(DSL.name("market_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "市场id|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.floor_code</code>. 楼层编码（int）|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, Long> FLOOR_CODE = createField(DSL.name("floor_code"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "楼层编码（int）|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.biz_id</code>. 档口表id|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, Long> BIZ_ID = createField(DSL.name("biz_id"), org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.BIGINT)), this, "档口表id|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.spu_name</code>. SPU名称|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, String> SPU_NAME = createField(DSL.name("spu_name"), org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "SPU名称|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.main_img_url</code>. 图片URL|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, String> MAIN_IMG_URL = createField(DSL.name("main_img_url"), org.jooq.impl.SQLDataType.VARCHAR(1024).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "图片URL|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.spu_goods_no</code>. 货号|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, String> SPU_GOODS_NO = createField(DSL.name("spu_goods_no"), org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "货号|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.total_fetch</code>. 总已拿货结账数量|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, BigDecimal> TOTAL_FETCH = createField(DSL.name("total_fetch"), org.jooq.impl.SQLDataType.DECIMAL(19, 4).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.0000", org.jooq.impl.SQLDataType.DECIMAL)), this, "总已拿货结账数量|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.total_return</code>. 总已退货结账数量|郑保乐|2021-06-08
     */
    public final TableField<PlatformSpuRecord, BigDecimal> TOTAL_RETURN = createField(DSL.name("total_return"), org.jooq.impl.SQLDataType.DECIMAL(19, 4).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.0000", org.jooq.impl.SQLDataType.DECIMAL)), this, "总已退货结账数量|郑保乐|2021-06-08");

    /**
     * The column <code>fdk_forwarder2.platform_spu.created</code>.
     */
    public final TableField<PlatformSpuRecord, Timestamp> CREATED = createField(DSL.name("created"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>fdk_forwarder2.platform_spu.modified</code>.
     */
    public final TableField<PlatformSpuRecord, Timestamp> MODIFIED = createField(DSL.name("modified"), org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>fdk_forwarder2.platform_spu</code> table reference
     */
    public PlatformSpu() {
        this(DSL.name("platform_spu"), null);
    }

    /**
     * Create an aliased <code>fdk_forwarder2.platform_spu</code> table reference
     */
    public PlatformSpu(String alias) {
        this(DSL.name(alias), PLATFORM_SPU);
    }

    /**
     * Create an aliased <code>fdk_forwarder2.platform_spu</code> table reference
     */
    public PlatformSpu(Name alias) {
        this(alias, PLATFORM_SPU);
    }

    private PlatformSpu(Name alias, Table<PlatformSpuRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlatformSpu(Name alias, Table<PlatformSpuRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("系统货品|郑保乐|2021-06-08"));
    }

    public <O extends Record> PlatformSpu(Table<O> child, ForeignKey<O, PlatformSpuRecord> key) {
        super(child, key, PLATFORM_SPU);
    }

    @Override
    public Schema getSchema() {
        return FdkForwarder2.FDK_FORWARDER2;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PLATFORM_SPU_IDX_BIZID_SPUGOODSNO, Indexes.PLATFORM_SPU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID, Indexes.PLATFORM_SPU_PRIMARY);
    }

    @Override
    public Identity<PlatformSpuRecord, Long> getIdentity() {
        return Keys.IDENTITY_PLATFORM_SPU;
    }

    @Override
    public UniqueKey<PlatformSpuRecord> getPrimaryKey() {
        return Keys.KEY_PLATFORM_SPU_PRIMARY;
    }

    @Override
    public List<UniqueKey<PlatformSpuRecord>> getKeys() {
        return Arrays.<UniqueKey<PlatformSpuRecord>>asList(Keys.KEY_PLATFORM_SPU_PRIMARY);
    }

    @Override
    public PlatformSpu as(String alias) {
        return new PlatformSpu(DSL.name(alias), this);
    }

    @Override
    public PlatformSpu as(Name alias) {
        return new PlatformSpu(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlatformSpu rename(String name) {
        return new PlatformSpu(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlatformSpu rename(Name name) {
        return new PlatformSpu(name, null);
    }

    // -------------------------------------------------------------------------
    // Row12 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row12<Long, Long, Long, Long, Long, String, String, String, BigDecimal, BigDecimal, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }
}
