/*
 * This file is generated by jOOQ.
 */
package com.huice.service_fdk.myjooq.db.tables.records;


import com.huice.service_fdk.myjooq.db.tables.MapSellerSkuSupplier;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;

import java.math.BigDecimal;
import java.time.LocalDateTime;


/**
 * 销售商SKU与供货商关联关系|刘宇晴|2020-11-20
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MapSellerSkuSupplierRecord extends UpdatableRecordImpl<MapSellerSkuSupplierRecord> implements Record18<Long, Long, Long, Long, Long, Long, Byte, String, String, BigDecimal, LocalDateTime, LocalDateTime, String, String, String, String, String, Byte> {

    private static final long serialVersionUID = 2122753401;

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.merchant_id</code>. 商户id |刘宇晴|2021-06-02
     */
    public void setMerchantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.merchant_id</code>. 商户id |刘宇晴|2021-06-02
     */
    public Long getMerchantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.seller_sku_id</code>. 销售商sku id|刘宇晴|2021-06-02
     */
    public void setSellerSkuId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.seller_sku_id</code>. 销售商sku id|刘宇晴|2021-06-02
     */
    public Long getSellerSkuId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.seller_spu_id</code>. 销售商spu_id|孟炜彬|2021-06-03
     */
    public void setSellerSpuId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.seller_spu_id</code>. 销售商spu_id|孟炜彬|2021-06-03
     */
    public Long getSellerSpuId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.supplier_id</code>. 供货商id|刘宇晴|2021-06-02
     */
    public void setSupplierId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.supplier_id</code>. 供货商id|刘宇晴|2021-06-02
     */
    public Long getSupplierId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.supplier_merchant_id</code>. 供货商的商户id|刘宇晴|2021-06-02
     */
    public void setSupplierMerchantId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.supplier_merchant_id</code>. 供货商的商户id|刘宇晴|2021-06-02
     */
    public Long getSupplierMerchantId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.main_flag</code>. 主从供货商标识0主供货商；1从供货商|刘宇晴|2021-06-02
     */
    public void setMainFlag(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.main_flag</code>. 主从供货商标识0主供货商；1从供货商|刘宇晴|2021-06-02
     */
    public Byte getMainFlag() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.remark</code>. 备注|刘宇晴|2021-06-02
     */
    public void setRemark(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.remark</code>. 备注|刘宇晴|2021-06-02
     */
    public String getRemark() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.item_no</code>. 货号|刘宇晴|2021-06-02
     */
    public void setItemNo(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.item_no</code>. 货号|刘宇晴|2021-06-02
     */
    public String getItemNo() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.purchase_price</code>. 拿货价|刘宇晴|2021-06-02
     */
    public void setPurchasePrice(BigDecimal value) {
        set(9, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.purchase_price</code>. 拿货价|刘宇晴|2021-06-02
     */
    public BigDecimal getPurchasePrice() {
        return (BigDecimal) get(9);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.modified</code>.
     */
    public void setModified(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.modified</code>.
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.city</code>. 城市 |刘宇晴|2021-06-08
     */
    public void setCity(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.city</code>. 城市 |刘宇晴|2021-06-08
     */
    public String getCity() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.market</code>. 市场 |刘宇晴|2021-06-08
     */
    public void setMarket(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.market</code>. 市场 |刘宇晴|2021-06-08
     */
    public String getMarket() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.floor</code>. 楼层 |刘宇晴|2021-06-08
     */
    public void setFloor(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.floor</code>. 楼层 |刘宇晴|2021-06-08
     */
    public String getFloor() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.business</code>. 档口 |刘宇晴|2021-06-08
     */
    public void setBusiness(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.business</code>. 档口 |刘宇晴|2021-06-08
     */
    public String getBusiness() {
        return (String) get(15);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.supplier_name</code>. 供货商全名 |刘宇晴|2021-06-08
     */
    public void setSupplierName(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.supplier_name</code>. 供货商全名 |刘宇晴|2021-06-08
     */
    public String getSupplierName() {
        return (String) get(16);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_sku_supplier.take_goods_type</code>. 子单中的货品拿货类型 @0 自拿；@1 代拿|刘宇晴|2021-06-08
     */
    public void setTakeGoodsType(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_sku_supplier.take_goods_type</code>. 子单中的货品拿货类型 @0 自拿；@1 代拿|刘宇晴|2021-06-08
     */
    public Byte getTakeGoodsType() {
        return (Byte) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row18<Long, Long, Long, Long, Long, Long, Byte, String, String, BigDecimal, LocalDateTime, LocalDateTime, String, String, String, String, String, Byte> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    @Override
    public Row18<Long, Long, Long, Long, Long, Long, Byte, String, String, BigDecimal, LocalDateTime, LocalDateTime, String, String, String, String, String, Byte> valuesRow() {
        return (Row18) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.ID;
    }

    @Override
    public Field<Long> field2() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.MERCHANT_ID;
    }

    @Override
    public Field<Long> field3() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.SELLER_SKU_ID;
    }

    @Override
    public Field<Long> field4() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.SELLER_SPU_ID;
    }

    @Override
    public Field<Long> field5() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.SUPPLIER_ID;
    }

    @Override
    public Field<Long> field6() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.SUPPLIER_MERCHANT_ID;
    }

    @Override
    public Field<Byte> field7() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.MAIN_FLAG;
    }

    @Override
    public Field<String> field8() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.REMARK;
    }

    @Override
    public Field<String> field9() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.ITEM_NO;
    }

    @Override
    public Field<BigDecimal> field10() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.PURCHASE_PRICE;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.CREATED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.MODIFIED;
    }

    @Override
    public Field<String> field13() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.CITY;
    }

    @Override
    public Field<String> field14() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.MARKET;
    }

    @Override
    public Field<String> field15() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.FLOOR;
    }

    @Override
    public Field<String> field16() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.BUSINESS;
    }

    @Override
    public Field<String> field17() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.SUPPLIER_NAME;
    }

    @Override
    public Field<Byte> field18() {
        return MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER.TAKE_GOODS_TYPE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMerchantId();
    }

    @Override
    public Long component3() {
        return getSellerSkuId();
    }

    @Override
    public Long component4() {
        return getSellerSpuId();
    }

    @Override
    public Long component5() {
        return getSupplierId();
    }

    @Override
    public Long component6() {
        return getSupplierMerchantId();
    }

    @Override
    public Byte component7() {
        return getMainFlag();
    }

    @Override
    public String component8() {
        return getRemark();
    }

    @Override
    public String component9() {
        return getItemNo();
    }

    @Override
    public BigDecimal component10() {
        return getPurchasePrice();
    }

    @Override
    public LocalDateTime component11() {
        return getCreated();
    }

    @Override
    public LocalDateTime component12() {
        return getModified();
    }

    @Override
    public String component13() {
        return getCity();
    }

    @Override
    public String component14() {
        return getMarket();
    }

    @Override
    public String component15() {
        return getFloor();
    }

    @Override
    public String component16() {
        return getBusiness();
    }

    @Override
    public String component17() {
        return getSupplierName();
    }

    @Override
    public Byte component18() {
        return getTakeGoodsType();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMerchantId();
    }

    @Override
    public Long value3() {
        return getSellerSkuId();
    }

    @Override
    public Long value4() {
        return getSellerSpuId();
    }

    @Override
    public Long value5() {
        return getSupplierId();
    }

    @Override
    public Long value6() {
        return getSupplierMerchantId();
    }

    @Override
    public Byte value7() {
        return getMainFlag();
    }

    @Override
    public String value8() {
        return getRemark();
    }

    @Override
    public String value9() {
        return getItemNo();
    }

    @Override
    public BigDecimal value10() {
        return getPurchasePrice();
    }

    @Override
    public LocalDateTime value11() {
        return getCreated();
    }

    @Override
    public LocalDateTime value12() {
        return getModified();
    }

    @Override
    public String value13() {
        return getCity();
    }

    @Override
    public String value14() {
        return getMarket();
    }

    @Override
    public String value15() {
        return getFloor();
    }

    @Override
    public String value16() {
        return getBusiness();
    }

    @Override
    public String value17() {
        return getSupplierName();
    }

    @Override
    public Byte value18() {
        return getTakeGoodsType();
    }

    @Override
    public MapSellerSkuSupplierRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value2(Long value) {
        setMerchantId(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value3(Long value) {
        setSellerSkuId(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value4(Long value) {
        setSellerSpuId(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value5(Long value) {
        setSupplierId(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value6(Long value) {
        setSupplierMerchantId(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value7(Byte value) {
        setMainFlag(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value8(String value) {
        setRemark(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value9(String value) {
        setItemNo(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value10(BigDecimal value) {
        setPurchasePrice(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value11(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value12(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value13(String value) {
        setCity(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value14(String value) {
        setMarket(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value15(String value) {
        setFloor(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value16(String value) {
        setBusiness(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value17(String value) {
        setSupplierName(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord value18(Byte value) {
        setTakeGoodsType(value);
        return this;
    }

    @Override
    public MapSellerSkuSupplierRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, Byte value7, String value8, String value9, BigDecimal value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14, String value15, String value16, String value17, Byte value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapSellerSkuSupplierRecord
     */
    public MapSellerSkuSupplierRecord() {
        super(MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER);
    }

    /**
     * Create a detached, initialised MapSellerSkuSupplierRecord
     */
    public MapSellerSkuSupplierRecord(Long id, Long merchantId, Long sellerSkuId, Long sellerSpuId, Long supplierId, Long supplierMerchantId, Byte mainFlag, String remark, String itemNo, BigDecimal purchasePrice, LocalDateTime created, LocalDateTime modified, String city, String market, String floor, String business, String supplierName, Byte takeGoodsType) {
        super(MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER);

        set(0, id);
        set(1, merchantId);
        set(2, sellerSkuId);
        set(3, sellerSpuId);
        set(4, supplierId);
        set(5, supplierMerchantId);
        set(6, mainFlag);
        set(7, remark);
        set(8, itemNo);
        set(9, purchasePrice);
        set(10, created);
        set(11, modified);
        set(12, city);
        set(13, market);
        set(14, floor);
        set(15, business);
        set(16, supplierName);
        set(17, takeGoodsType);
    }
}
