/*
 * This file is generated by jOOQ.
 */
package com.huice.service_fdk.myjooq.db.tables.records;


import com.huice.service_fdk.myjooq.db.tables.MapSellerSpuShop;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 销售商Spu与销售商店铺 关联关系|魏柯|2020-11-21
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MapSellerSpuShopRecord extends UpdatableRecordImpl<MapSellerSpuShopRecord> implements Record8<Long, Long, Long, LocalDateTime, LocalDateTime, Long, Byte, String> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.id</code>. 自增Id
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.id</code>. 自增Id
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.merchant_id</code>. 商户id|魏柯|2020-11-21
     */
    public void setMerchantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.merchant_id</code>. 商户id|魏柯|2020-11-21
     */
    public Long getMerchantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.seller_spu_id</code>. spu_id|魏柯|2020-11-21
     */
    public void setSellerSpuId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.seller_spu_id</code>. spu_id|魏柯|2020-11-21
     */
    public Long getSellerSpuId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.created</code>.
     */
    public void setCreated(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.created</code>.
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.modified</code>. 更新时间
     */
    public void setModified(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.modified</code>. 更新时间
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.shop_id</code>. 店铺id|魏柯|2020-11-21
     */
    public void setShopId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.shop_id</code>. 店铺id|魏柯|2020-11-21
     */
    public Long getShopId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.delivery_time_type</code>. 发货时限类型 @0不设置; @1 付款后xx小时；@2 指定时间xx之前；@3 应用店铺发货时限  |孟炜彬|2021-06-01
     */
    public void setDeliveryTimeType(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.delivery_time_type</code>. 发货时限类型 @0不设置; @1 付款后xx小时；@2 指定时间xx之前；@3 应用店铺发货时限  |孟炜彬|2021-06-01
     */
    public Byte getDeliveryTimeType() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>fdk_goods2.map_seller_spu_shop.delivery_time_description</code>. 发货时限时长描述。 整数则为 1类型 小时，时间则为2类型 指定时间之前|孟炜彬|2021-06-01
     */
    public void setDeliveryTimeDescription(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_goods2.map_seller_spu_shop.delivery_time_description</code>. 发货时限时长描述。 整数则为 1类型 小时，时间则为2类型 指定时间之前|孟炜彬|2021-06-01
     */
    public String getDeliveryTimeDescription() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, LocalDateTime, LocalDateTime, Long, Byte, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Long, LocalDateTime, LocalDateTime, Long, Byte, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.ID;
    }

    @Override
    public Field<Long> field2() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.MERCHANT_ID;
    }

    @Override
    public Field<Long> field3() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.SELLER_SPU_ID;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.CREATED;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.MODIFIED;
    }

    @Override
    public Field<Long> field6() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.SHOP_ID;
    }

    @Override
    public Field<Byte> field7() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.DELIVERY_TIME_TYPE;
    }

    @Override
    public Field<String> field8() {
        return MapSellerSpuShop.MAP_SELLER_SPU_SHOP.DELIVERY_TIME_DESCRIPTION;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMerchantId();
    }

    @Override
    public Long component3() {
        return getSellerSpuId();
    }

    @Override
    public LocalDateTime component4() {
        return getCreated();
    }

    @Override
    public LocalDateTime component5() {
        return getModified();
    }

    @Override
    public Long component6() {
        return getShopId();
    }

    @Override
    public Byte component7() {
        return getDeliveryTimeType();
    }

    @Override
    public String component8() {
        return getDeliveryTimeDescription();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMerchantId();
    }

    @Override
    public Long value3() {
        return getSellerSpuId();
    }

    @Override
    public LocalDateTime value4() {
        return getCreated();
    }

    @Override
    public LocalDateTime value5() {
        return getModified();
    }

    @Override
    public Long value6() {
        return getShopId();
    }

    @Override
    public Byte value7() {
        return getDeliveryTimeType();
    }

    @Override
    public String value8() {
        return getDeliveryTimeDescription();
    }

    @Override
    public MapSellerSpuShopRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value2(Long value) {
        setMerchantId(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value3(Long value) {
        setSellerSpuId(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value4(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value5(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value6(Long value) {
        setShopId(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value7(Byte value) {
        setDeliveryTimeType(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord value8(String value) {
        setDeliveryTimeDescription(value);
        return this;
    }

    @Override
    public MapSellerSpuShopRecord values(Long value1, Long value2, Long value3, LocalDateTime value4, LocalDateTime value5, Long value6, Byte value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MapSellerSpuShopRecord
     */
    public MapSellerSpuShopRecord() {
        super(MapSellerSpuShop.MAP_SELLER_SPU_SHOP);
    }

    /**
     * Create a detached, initialised MapSellerSpuShopRecord
     */
    public MapSellerSpuShopRecord(Long id, Long merchantId, Long sellerSpuId, LocalDateTime created, LocalDateTime modified, Long shopId, Byte deliveryTimeType, String deliveryTimeDescription) {
        super(MapSellerSpuShop.MAP_SELLER_SPU_SHOP);

        setId(id);
        setMerchantId(merchantId);
        setSellerSpuId(sellerSpuId);
        setCreated(created);
        setModified(modified);
        setShopId(shopId);
        setDeliveryTimeType(deliveryTimeType);
        setDeliveryTimeDescription(deliveryTimeDescription);
    }
}
