/*
 * This file is generated by jOOQ.
 */
package com.huice.service_fdk.myjooq.db.tables.records;


import com.huice.service_fdk.myjooq.db.tables.PlatformSku;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * 平台货品SKU表|牛振宇|2020-11-03
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlatformSkuRecord extends UpdatableRecordImpl<PlatformSkuRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fdk_goods2.platform_sku.id</code>. 自增ID|牛振宇|2020-11-24
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.id</code>. 自增ID|牛振宇|2020-11-24
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.merchant_id</code>. 商户id|牛振宇|2020-11-03
     */
    public void setMerchantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.merchant_id</code>. 商户id|牛振宇|2020-11-03
     */
    public Long getMerchantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.sale_status</code>. 在售状态｜ @1：在架 @2：下架 @3：店铺已删除 @4：自建默认显示 "/" | 魏柯 | 2020-12-10
     */
    public void setSaleStatus(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.sale_status</code>. 在售状态｜ @1：在架 @2：下架 @3：店铺已删除 @4：自建默认显示 "/" | 魏柯 | 2020-12-10
     */
    public Byte getSaleStatus() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.platform_id</code>. 平台id|牛振宇|2020-12-10
     */
    public void setPlatformId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.platform_id</code>. 平台id|牛振宇|2020-12-10
     */
    public Integer getPlatformId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.platform_name</code>. 平台名称|牛振宇|2020-11-10
     */
    public void setPlatformName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.platform_name</code>. 平台名称|牛振宇|2020-11-10
     */
    public String getPlatformName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.shop_id</code>. 店铺id|牛振宇|2020-11-03
     */
    public void setShopId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.shop_id</code>. 店铺id|牛振宇|2020-11-03
     */
    public Long getShopId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.goods_id</code>. 平台货品id|牛振宇|2020-11-03
     */
    public void setGoodsId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.goods_id</code>. 平台货品id|牛振宇|2020-11-03
     */
    public String getGoodsId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.goods_name</code>. 平台货品名称|牛振宇|2020-11-03
     */
    public void setGoodsName(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.goods_name</code>. 平台货品名称|牛振宇|2020-11-03
     */
    public String getGoodsName() {
        return (String) get(7);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.sku_id</code>. 平台skuid|牛振宇|2020-11-03
     */
    public void setSkuId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.sku_id</code>. 平台skuid|牛振宇|2020-11-03
     */
    public String getSkuId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.sku_code</code>. 平台规格码|牛振宇|2020-11-03
     */
    public void setSkuCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.sku_code</code>. 平台规格码|牛振宇|2020-11-03
     */
    public String getSkuCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.sku_name</code>. 平台规格名|牛振宇|2020-11-03
     */
    public void setSkuName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.sku_name</code>. 平台规格名|牛振宇|2020-11-03
     */
    public String getSkuName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.sku_properties</code>. 平台sku属性串,如 1627207:3232483;1630696:3284570|牛振宇|2020-11-03
     */
    public void setSkuProperties(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.sku_properties</code>. 平台sku属性串,如 1627207:3232483;1630696:3284570|牛振宇|2020-11-03
     */
    public String getSkuProperties() {
        return (String) get(11);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.outer_id</code>. 商家编码(spu维度)|牛振宇|2020-11-10
     */
    public void setOuterId(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.outer_id</code>. 商家编码(spu维度)|牛振宇|2020-11-10
     */
    public String getOuterId() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.sku_outer_id</code>. 规格商家编码(sku维度)|牛振宇|2020-11-10
     */
    public void setSkuOuterId(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.sku_outer_id</code>. 规格商家编码(sku维度)|牛振宇|2020-11-10
     */
    public String getSkuOuterId() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.cid</code>. 平台类目|牛振宇|2020-11-03
     */
    public void setCid(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.cid</code>. 平台类目|牛振宇|2020-11-03
     */
    public String getCid() {
        return (String) get(14);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.price</code>. 平台售价，开启库存同步才准确|牛振宇|2020-11-03
     */
    public void setPrice(BigDecimal value) {
        set(15, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.price</code>. 平台售价，开启库存同步才准确|牛振宇|2020-11-03
     */
    public BigDecimal getPrice() {
        return (BigDecimal) get(15);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.stock_num</code>. 平台库存量，只有开启库存同步的货品才准确|牛振宇|2020-11-03
     */
    public void setStockNum(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.stock_num</code>. 平台库存量，只有开启库存同步的货品才准确|牛振宇|2020-11-03
     */
    public BigDecimal getStockNum() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.img_url</code>. 图片url|牛振宇|2020-11-03
     */
    public void setImgUrl(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.img_url</code>. 图片url|牛振宇|2020-11-03
     */
    public String getImgUrl() {
        return (String) get(17);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.barcode</code>. 平台上的条码,多个条码用逗号分隔|牛振宇|2020-11-03
     */
    public void setBarcode(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.barcode</code>. 平台上的条码,多个条码用逗号分隔|牛振宇|2020-11-03
     */
    public String getBarcode() {
        return (String) get(18);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.hold_stock_type</code>. 扣减库存方式：1拍下减库存 2付款减库存|牛振宇|2020-11-03
     */
    public void setHoldStockType(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.hold_stock_type</code>. 扣减库存方式：1拍下减库存 2付款减库存|牛振宇|2020-11-03
     */
    public Byte getHoldStockType() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.hold_stock</code>. 占用库存量|牛振宇|2020-11-03
     */
    public void setHoldStock(BigDecimal value) {
        set(20, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.hold_stock</code>. 占用库存量|牛振宇|2020-11-03
     */
    public BigDecimal getHoldStock() {
        return (BigDecimal) get(20);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.modify_mask</code>. 修改标记，平台货品信息发生变化置为1|牛振宇|2020-11-03
     */
    public void setModifyMask(Integer value) {
        set(21, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.modify_mask</code>. 修改标记，平台货品信息发生变化置为1|牛振宇|2020-11-03
     */
    public Integer getModifyMask() {
        return (Integer) get(21);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.delete_flag</code>. 删除标志|@0未删除；@1已删除|牛振宇|2020-11-20
     */
    public void setDeleteFlag(Byte value) {
        set(22, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.delete_flag</code>. 删除标志|@0未删除；@1已删除|牛振宇|2020-11-20
     */
    public Byte getDeleteFlag() {
        return (Byte) get(22);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.created</code>. 创建时间|牛振宇|2020-11-03
     */
    public void setCreated(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.created</code>. 创建时间|牛振宇|2020-11-03
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.modified</code>. 更新时间|牛振宇|2020-11-03
     */
    public void setModified(LocalDateTime value) {
        set(24, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.modified</code>. 更新时间|牛振宇|2020-11-03
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(24);
    }

    /**
     * Setter for <code>fdk_goods2.platform_sku.main_img_url</code>. 主图url|牛振宇|2021-06-29
     */
    public void setMainImgUrl(String value) {
        set(25, value);
    }

    /**
     * Getter for <code>fdk_goods2.platform_sku.main_img_url</code>. 主图url|牛振宇|2021-06-29
     */
    public String getMainImgUrl() {
        return (String) get(25);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlatformSkuRecord
     */
    public PlatformSkuRecord() {
        super(PlatformSku.PLATFORM_SKU);
    }

    /**
     * Create a detached, initialised PlatformSkuRecord
     */
    public PlatformSkuRecord(ULong id, Long merchantId, Byte saleStatus, Integer platformId, String platformName, Long shopId, String goodsId, String goodsName, String skuId, String skuCode, String skuName, String skuProperties, String outerId, String skuOuterId, String cid, BigDecimal price, BigDecimal stockNum, String imgUrl, String barcode, Byte holdStockType, BigDecimal holdStock, Integer modifyMask, Byte deleteFlag, LocalDateTime created, LocalDateTime modified, String mainImgUrl) {
        super(PlatformSku.PLATFORM_SKU);

        setId(id);
        setMerchantId(merchantId);
        setSaleStatus(saleStatus);
        setPlatformId(platformId);
        setPlatformName(platformName);
        setShopId(shopId);
        setGoodsId(goodsId);
        setGoodsName(goodsName);
        setSkuId(skuId);
        setSkuCode(skuCode);
        setSkuName(skuName);
        setSkuProperties(skuProperties);
        setOuterId(outerId);
        setSkuOuterId(skuOuterId);
        setCid(cid);
        setPrice(price);
        setStockNum(stockNum);
        setImgUrl(imgUrl);
        setBarcode(barcode);
        setHoldStockType(holdStockType);
        setHoldStock(holdStock);
        setModifyMask(modifyMask);
        setDeleteFlag(deleteFlag);
        setCreated(created);
        setModified(modified);
        setMainImgUrl(mainImgUrl);
    }
}
