/*
 * This file is generated by jOOQ.
 */
package com.huice.service_fdk.myjooq.db.tables.records;


import com.huice.service_fdk.myjooq.db.tables.SellerSpuImg;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * spu图片列表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SellerSpuImgRecord extends UpdatableRecordImpl<SellerSpuImgRecord> implements Record7<Long, Long, Long, String, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.id</code>. 自增ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.id</code>. 自增ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.merchant_id</code>. 销售商/供货商商户id|牛振宇|2020-11-20
     */
    public void setMerchantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.merchant_id</code>. 销售商/供货商商户id|牛振宇|2020-11-20
     */
    public Long getMerchantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.spu_id</code>. 销售商/供货商spuId|牛振宇|2020-11-20
     */
    public void setSpuId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.spu_id</code>. 销售商/供货商spuId|牛振宇|2020-11-20
     */
    public Long getSpuId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.img_url</code>. 图片url|牛振宇|2020-11-20
     */
    public void setImgUrl(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.img_url</code>. 图片url|牛振宇|2020-11-20
     */
    public String getImgUrl() {
        return (String) get(3);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.delete_flag</code>. 软删除|@0：未删除；@1：已删除|牛振宇|2020-11-20
     */
    public void setDeleteFlag(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.delete_flag</code>. 软删除|@0：未删除；@1：已删除|牛振宇|2020-11-20
     */
    public Byte getDeleteFlag() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.created</code>. 创建时间|牛振宇|2020-11-20
     */
    public void setCreated(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.created</code>. 创建时间|牛振宇|2020-11-20
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu_img.modified</code>. 修改时间|牛振宇|2020-11-20
     */
    public void setModified(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu_img.modified</code>. 修改时间|牛振宇|2020-11-20
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, String, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, String, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SellerSpuImg.SELLER_SPU_IMG.ID;
    }

    @Override
    public Field<Long> field2() {
        return SellerSpuImg.SELLER_SPU_IMG.MERCHANT_ID;
    }

    @Override
    public Field<Long> field3() {
        return SellerSpuImg.SELLER_SPU_IMG.SPU_ID;
    }

    @Override
    public Field<String> field4() {
        return SellerSpuImg.SELLER_SPU_IMG.IMG_URL;
    }

    @Override
    public Field<Byte> field5() {
        return SellerSpuImg.SELLER_SPU_IMG.DELETE_FLAG;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SellerSpuImg.SELLER_SPU_IMG.CREATED;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return SellerSpuImg.SELLER_SPU_IMG.MODIFIED;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMerchantId();
    }

    @Override
    public Long component3() {
        return getSpuId();
    }

    @Override
    public String component4() {
        return getImgUrl();
    }

    @Override
    public Byte component5() {
        return getDeleteFlag();
    }

    @Override
    public LocalDateTime component6() {
        return getCreated();
    }

    @Override
    public LocalDateTime component7() {
        return getModified();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMerchantId();
    }

    @Override
    public Long value3() {
        return getSpuId();
    }

    @Override
    public String value4() {
        return getImgUrl();
    }

    @Override
    public Byte value5() {
        return getDeleteFlag();
    }

    @Override
    public LocalDateTime value6() {
        return getCreated();
    }

    @Override
    public LocalDateTime value7() {
        return getModified();
    }

    @Override
    public SellerSpuImgRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord value2(Long value) {
        setMerchantId(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord value3(Long value) {
        setSpuId(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord value4(String value) {
        setImgUrl(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord value5(Byte value) {
        setDeleteFlag(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord value6(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord value7(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public SellerSpuImgRecord values(Long value1, Long value2, Long value3, String value4, Byte value5, LocalDateTime value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SellerSpuImgRecord
     */
    public SellerSpuImgRecord() {
        super(SellerSpuImg.SELLER_SPU_IMG);
    }

    /**
     * Create a detached, initialised SellerSpuImgRecord
     */
    public SellerSpuImgRecord(Long id, Long merchantId, Long spuId, String imgUrl, Byte deleteFlag, LocalDateTime created, LocalDateTime modified) {
        super(SellerSpuImg.SELLER_SPU_IMG);

        setId(id);
        setMerchantId(merchantId);
        setSpuId(spuId);
        setImgUrl(imgUrl);
        setDeleteFlag(deleteFlag);
        setCreated(created);
        setModified(modified);
    }
}
