/*
 * This file is generated by jOOQ.
 */
package com.huice.service_fdk.myjooq.db.tables.records;


import com.huice.service_fdk.myjooq.db.tables.SellerSpu;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 销售商货品SPU|郑保乐|2020-11-20
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SellerSpuRecord extends UpdatableRecordImpl<SellerSpuRecord> implements Record17<Long, Long, String, Integer, String, String, Byte, Byte, Long, Byte, LocalDateTime, LocalDateTime, String, String, Byte, Byte, String> {

    private static final long serialVersionUID = -970254536;

    /**
     * Setter for <code>fdk_goods2.seller_spu.id</code>. id|郑保乐|2020-11-20
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.id</code>. id|郑保乐|2020-11-20
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.merchant_id</code>. 商户id|郑保乐|2020-11-23
     */
    public void setMerchantId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.merchant_id</code>. 商户id|郑保乐|2020-11-23
     */
    public Long getMerchantId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.spu_name</code>. 货品名称|郑保乐|2020-11-20
     */
    public void setSpuName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.spu_name</code>. 货品名称|郑保乐|2020-11-20
     */
    public String getSpuName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.platform_id</code>. 平台id|牛振宇|2020-12-10
     */
    public void setPlatformId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.platform_id</code>. 平台id|牛振宇|2020-12-10
     */
    public Integer getPlatformId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.goods_id</code>. 平台货品id|牛振宇|2020-11-30
     */
    public void setGoodsId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.goods_id</code>. 平台货品id|牛振宇|2020-11-30
     */
    public String getGoodsId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.goods_no</code>. 货品商家编码|郑保乐|2020-11-20
     */
    public void setGoodsNo(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.goods_no</code>. 货品商家编码|郑保乐|2020-11-20
     */
    public String getGoodsNo() {
        return (String) get(5);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.source</code>. 来源|@1 来自平台订单 @2来自平台下载 @3 盘TA 后生成的@4 销售商自建|郑保乐|2020-11-27
     */
    public void setSource(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.source</code>. 来源|@1 来自平台订单 @2来自平台下载 @3 盘TA 后生成的@4 销售商自建|郑保乐|2020-11-27
     */
    public Byte getSource() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.show_flag</code>. 是否显示在货品列表|@0 否 @1 是|郑保乐|2020-11-20
     */
    public void setShowFlag(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.show_flag</code>. 是否显示在货品列表|@0 否 @1 是|郑保乐|2020-11-20
     */
    public Byte getShowFlag() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.pid</code>. 关联的货品id|郑保乐|2020-11-20
     */
    public void setPid(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.pid</code>. 关联的货品id|郑保乐|2020-11-20
     */
    public Long getPid() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.sale_status</code>. 在售状态｜ @1：在架 @2：下架 @3：店铺已删除 @4：自建默认显示 "/" | 魏柯 | 2020-12-10
     */
    public void setSaleStatus(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.sale_status</code>. 在售状态｜ @1：在架 @2：下架 @3：店铺已删除 @4：自建默认显示 "/" | 魏柯 | 2020-12-10
     */
    public Byte getSaleStatus() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.created</code>. 创建时间
     */
    public void setCreated(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.created</code>. 创建时间
     */
    public LocalDateTime getCreated() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.modified</code>. 修改时间
     */
    public void setModified(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.modified</code>. 修改时间
     */
    public LocalDateTime getModified() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.main_img_url</code>. spu主图|王明亮|2020年12月26日
     */
    public void setMainImgUrl(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.main_img_url</code>. spu主图|王明亮|2020年12月26日
     */
    public String getMainImgUrl() {
        return (String) get(12);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.spu_goods_no</code>. 货号|刘宇晴|2021-03-04
     */
    public void setSpuGoodsNo(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.spu_goods_no</code>. 货号|刘宇晴|2021-03-04
     */
    public String getSpuGoodsNo() {
        return (String) get(13);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.pack_flag</code>. 组合装标识 @0:无组合装 @1:有组合装|郑保乐|2021-04-20
     */
    public void setPackFlag(Byte value) {
        set(14, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.pack_flag</code>. 组合装标识 @0:无组合装 @1:有组合装|郑保乐|2021-04-20
     */
    public Byte getPackFlag() {
        return (Byte) get(14);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.stagnant_flag</code>. 滞销货品标识 @0：正常货品 @1：滞销货品 | 孟炜彬 | 2021-05-11
     */
    public void setStagnantFlag(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.stagnant_flag</code>. 滞销货品标识 @0：正常货品 @1：滞销货品 | 孟炜彬 | 2021-05-11
     */
    public Byte getStagnantFlag() {
        return (Byte) get(15);
    }

    /**
     * Setter for <code>fdk_goods2.seller_spu.goods_link</code>. 宝贝链接
     */
    public void setGoodsLink(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>fdk_goods2.seller_spu.goods_link</code>. 宝贝链接
     */
    public String getGoodsLink() {
        return (String) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, Long, String, Integer, String, String, Byte, Byte, Long, Byte, LocalDateTime, LocalDateTime, String, String, Byte, Byte, String> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Long, Long, String, Integer, String, String, Byte, Byte, Long, Byte, LocalDateTime, LocalDateTime, String, String, Byte, Byte, String> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SellerSpu.SELLER_SPU.ID;
    }

    @Override
    public Field<Long> field2() {
        return SellerSpu.SELLER_SPU.MERCHANT_ID;
    }

    @Override
    public Field<String> field3() {
        return SellerSpu.SELLER_SPU.SPU_NAME;
    }

    @Override
    public Field<Integer> field4() {
        return SellerSpu.SELLER_SPU.PLATFORM_ID;
    }

    @Override
    public Field<String> field5() {
        return SellerSpu.SELLER_SPU.GOODS_ID;
    }

    @Override
    public Field<String> field6() {
        return SellerSpu.SELLER_SPU.GOODS_NO;
    }

    @Override
    public Field<Byte> field7() {
        return SellerSpu.SELLER_SPU.SOURCE;
    }

    @Override
    public Field<Byte> field8() {
        return SellerSpu.SELLER_SPU.SHOW_FLAG;
    }

    @Override
    public Field<Long> field9() {
        return SellerSpu.SELLER_SPU.PID;
    }

    @Override
    public Field<Byte> field10() {
        return SellerSpu.SELLER_SPU.SALE_STATUS;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return SellerSpu.SELLER_SPU.CREATED;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return SellerSpu.SELLER_SPU.MODIFIED;
    }

    @Override
    public Field<String> field13() {
        return SellerSpu.SELLER_SPU.MAIN_IMG_URL;
    }

    @Override
    public Field<String> field14() {
        return SellerSpu.SELLER_SPU.SPU_GOODS_NO;
    }

    @Override
    public Field<Byte> field15() {
        return SellerSpu.SELLER_SPU.PACK_FLAG;
    }

    @Override
    public Field<Byte> field16() {
        return SellerSpu.SELLER_SPU.STAGNANT_FLAG;
    }

    @Override
    public Field<String> field17() {
        return SellerSpu.SELLER_SPU.GOODS_LINK;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getMerchantId();
    }

    @Override
    public String component3() {
        return getSpuName();
    }

    @Override
    public Integer component4() {
        return getPlatformId();
    }

    @Override
    public String component5() {
        return getGoodsId();
    }

    @Override
    public String component6() {
        return getGoodsNo();
    }

    @Override
    public Byte component7() {
        return getSource();
    }

    @Override
    public Byte component8() {
        return getShowFlag();
    }

    @Override
    public Long component9() {
        return getPid();
    }

    @Override
    public Byte component10() {
        return getSaleStatus();
    }

    @Override
    public LocalDateTime component11() {
        return getCreated();
    }

    @Override
    public LocalDateTime component12() {
        return getModified();
    }

    @Override
    public String component13() {
        return getMainImgUrl();
    }

    @Override
    public String component14() {
        return getSpuGoodsNo();
    }

    @Override
    public Byte component15() {
        return getPackFlag();
    }

    @Override
    public Byte component16() {
        return getStagnantFlag();
    }

    @Override
    public String component17() {
        return getGoodsLink();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getMerchantId();
    }

    @Override
    public String value3() {
        return getSpuName();
    }

    @Override
    public Integer value4() {
        return getPlatformId();
    }

    @Override
    public String value5() {
        return getGoodsId();
    }

    @Override
    public String value6() {
        return getGoodsNo();
    }

    @Override
    public Byte value7() {
        return getSource();
    }

    @Override
    public Byte value8() {
        return getShowFlag();
    }

    @Override
    public Long value9() {
        return getPid();
    }

    @Override
    public Byte value10() {
        return getSaleStatus();
    }

    @Override
    public LocalDateTime value11() {
        return getCreated();
    }

    @Override
    public LocalDateTime value12() {
        return getModified();
    }

    @Override
    public String value13() {
        return getMainImgUrl();
    }

    @Override
    public String value14() {
        return getSpuGoodsNo();
    }

    @Override
    public Byte value15() {
        return getPackFlag();
    }

    @Override
    public Byte value16() {
        return getStagnantFlag();
    }

    @Override
    public String value17() {
        return getGoodsLink();
    }

    @Override
    public SellerSpuRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SellerSpuRecord value2(Long value) {
        setMerchantId(value);
        return this;
    }

    @Override
    public SellerSpuRecord value3(String value) {
        setSpuName(value);
        return this;
    }

    @Override
    public SellerSpuRecord value4(Integer value) {
        setPlatformId(value);
        return this;
    }

    @Override
    public SellerSpuRecord value5(String value) {
        setGoodsId(value);
        return this;
    }

    @Override
    public SellerSpuRecord value6(String value) {
        setGoodsNo(value);
        return this;
    }

    @Override
    public SellerSpuRecord value7(Byte value) {
        setSource(value);
        return this;
    }

    @Override
    public SellerSpuRecord value8(Byte value) {
        setShowFlag(value);
        return this;
    }

    @Override
    public SellerSpuRecord value9(Long value) {
        setPid(value);
        return this;
    }

    @Override
    public SellerSpuRecord value10(Byte value) {
        setSaleStatus(value);
        return this;
    }

    @Override
    public SellerSpuRecord value11(LocalDateTime value) {
        setCreated(value);
        return this;
    }

    @Override
    public SellerSpuRecord value12(LocalDateTime value) {
        setModified(value);
        return this;
    }

    @Override
    public SellerSpuRecord value13(String value) {
        setMainImgUrl(value);
        return this;
    }

    @Override
    public SellerSpuRecord value14(String value) {
        setSpuGoodsNo(value);
        return this;
    }

    @Override
    public SellerSpuRecord value15(Byte value) {
        setPackFlag(value);
        return this;
    }

    @Override
    public SellerSpuRecord value16(Byte value) {
        setStagnantFlag(value);
        return this;
    }

    @Override
    public SellerSpuRecord value17(String value) {
        setGoodsLink(value);
        return this;
    }

    @Override
    public SellerSpuRecord values(Long value1, Long value2, String value3, Integer value4, String value5, String value6, Byte value7, Byte value8, Long value9, Byte value10, LocalDateTime value11, LocalDateTime value12, String value13, String value14, Byte value15, Byte value16, String value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SellerSpuRecord
     */
    public SellerSpuRecord() {
        super(SellerSpu.SELLER_SPU);
    }

    /**
     * Create a detached, initialised SellerSpuRecord
     */
    public SellerSpuRecord(Long id, Long merchantId, String spuName, Integer platformId, String goodsId, String goodsNo, Byte source, Byte showFlag, Long pid, Byte saleStatus, LocalDateTime created, LocalDateTime modified, String mainImgUrl, String spuGoodsNo, Byte packFlag, Byte stagnantFlag, String goodsLink) {
        super(SellerSpu.SELLER_SPU);

        set(0, id);
        set(1, merchantId);
        set(2, spuName);
        set(3, platformId);
        set(4, goodsId);
        set(5, goodsNo);
        set(6, source);
        set(7, showFlag);
        set(8, pid);
        set(9, saleStatus);
        set(10, created);
        set(11, modified);
        set(12, mainImgUrl);
        set(13, spuGoodsNo);
        set(14, packFlag);
        set(15, stagnantFlag);
        set(16, goodsLink);
    }
}
