/*
 * This file is generated by jOOQ.
 */
package com.huice.service_fdk.myjooq.db;


import com.huice.service_fdk.myjooq.db.tables.ForwarderSupplier;
import com.huice.service_fdk.myjooq.db.tables.MapSellerSkuSupplier;
import com.huice.service_fdk.myjooq.db.tables.MapSellerSpuShop;
import com.huice.service_fdk.myjooq.db.tables.PlatformSku;
import com.huice.service_fdk.myjooq.db.tables.PrepareSkuTag;
import com.huice.service_fdk.myjooq.db.tables.SellerOnPrepareSkuList;
import com.huice.service_fdk.myjooq.db.tables.SellerSku;
import com.huice.service_fdk.myjooq.db.tables.SellerSpu;
import com.huice.service_fdk.myjooq.db.tables.SellerSpuImg;
import com.huice.service_fdk.myjooq.db.tables.SellerToPrepareSkuList;
import com.huice.service_fdk.myjooq.db.tables.SysShop;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FdkGoods2 extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>fdk_goods2</code>
     */
    public static final FdkGoods2 FDK_GOODS2 = new FdkGoods2();

    /**
     * 销售商已创建的代拿供货商|刘宇晴|2021-06-08
     */
    public final ForwarderSupplier FORWARDER_SUPPLIER = ForwarderSupplier.FORWARDER_SUPPLIER;

    /**
     * 销售商SKU与供货商关联关系|刘宇晴|2020-11-20
     */
    public final MapSellerSkuSupplier MAP_SELLER_SKU_SUPPLIER = MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER;

    /**
     * 销售商Spu与销售商店铺 关联关系|魏柯|2020-11-21
     */
    public final MapSellerSpuShop MAP_SELLER_SPU_SHOP = MapSellerSpuShop.MAP_SELLER_SPU_SHOP;

    /**
     * 平台货品SKU表|牛振宇|2020-11-03
     */
    public final PlatformSku PLATFORM_SKU = PlatformSku.PLATFORM_SKU;

    /**
     * 拿货小标签|王明亮|2020-11-20
     */
    public final PrepareSkuTag PREPARE_SKU_TAG = PrepareSkuTag.PREPARE_SKU_TAG;

    /**
     * 销售商备货中列表|孟炜彬|2020-11-20
     */
    public final SellerOnPrepareSkuList SELLER_ON_PREPARE_SKU_LIST = SellerOnPrepareSkuList.SELLER_ON_PREPARE_SKU_LIST;

    /**
     * 销售商货品SKU表
     */
    public final SellerSku SELLER_SKU = SellerSku.SELLER_SKU;

    /**
     * 销售商货品SPU|郑保乐|2020-11-20
     */
    public final SellerSpu SELLER_SPU = SellerSpu.SELLER_SPU;

    /**
     * spu图片列表
     */
    public final SellerSpuImg SELLER_SPU_IMG = SellerSpuImg.SELLER_SPU_IMG;

    /**
     * 销售商待备货列表|孟炜彬|2020-11-20
     */
    public final SellerToPrepareSkuList SELLER_TO_PREPARE_SKU_LIST = SellerToPrepareSkuList.SELLER_TO_PREPARE_SKU_LIST;

    /**
     * 平台店铺表，商家自主创建记录基本信息和授权信息
     */
    public final SysShop SYS_SHOP = SysShop.SYS_SHOP;

    /**
     * No further instances allowed
     */
    private FdkGoods2() {
        super("fdk_goods2", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            ForwarderSupplier.FORWARDER_SUPPLIER,
            MapSellerSkuSupplier.MAP_SELLER_SKU_SUPPLIER,
            MapSellerSpuShop.MAP_SELLER_SPU_SHOP,
            PlatformSku.PLATFORM_SKU,
            PrepareSkuTag.PREPARE_SKU_TAG,
            SellerOnPrepareSkuList.SELLER_ON_PREPARE_SKU_LIST,
            SellerSku.SELLER_SKU,
            SellerSpu.SELLER_SPU,
            SellerSpuImg.SELLER_SPU_IMG,
            SellerToPrepareSkuList.SELLER_TO_PREPARE_SKU_LIST,
            SysShop.SYS_SHOP);
    }
}
