/*
 * This file is generated by jOOQ.
 */
package com.huice.service_forwarder.db;


import com.huice.service_forwarder.db.tables.BaseBusinessInfo;
import com.huice.service_forwarder.db.tables.PlatformSku;
import com.huice.service_forwarder.db.tables.PlatformSpu;
import com.huice.service_forwarder.db.tables.Seller;
import com.huice.service_forwarder.db.tables.SellerFetchOrder;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>fdk_forwarder2</code> 
 * schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index BASE_BUSINESS_INFO_PRIMARY = Indexes0.BASE_BUSINESS_INFO_PRIMARY;
    public static final Index BASE_BUSINESS_INFO_UK_BIZ_CODE = Indexes0.BASE_BUSINESS_INFO_UK_BIZ_CODE;
    public static final Index PLATFORM_SKU_IDX_BIZFULLNAME_SPUGOODSNO = Indexes0.PLATFORM_SKU_IDX_BIZFULLNAME_SPUGOODSNO;
    public static final Index PLATFORM_SKU_IDX_BIZID_SPUGOODSNO = Indexes0.PLATFORM_SKU_IDX_BIZID_SPUGOODSNO;
    public static final Index PLATFORM_SKU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID = Indexes0.PLATFORM_SKU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID;
    public static final Index PLATFORM_SKU_IDX_SPUID = Indexes0.PLATFORM_SKU_IDX_SPUID;
    public static final Index PLATFORM_SKU_PRIMARY = Indexes0.PLATFORM_SKU_PRIMARY;
    public static final Index PLATFORM_SPU_IDX_BIZID_SPUGOODSNO = Indexes0.PLATFORM_SPU_IDX_BIZID_SPUGOODSNO;
    public static final Index PLATFORM_SPU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID = Indexes0.PLATFORM_SPU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID;
    public static final Index PLATFORM_SPU_PRIMARY = Indexes0.PLATFORM_SPU_PRIMARY;
    public static final Index SELLER_PLATFORM_CODE = Indexes0.SELLER_PLATFORM_CODE;
    public static final Index SELLER_PRIMARY = Indexes0.SELLER_PRIMARY;
    public static final Index SELLER_SHORT_NAME = Indexes0.SELLER_SHORT_NAME;
    public static final Index SELLER_FETCH_ORDER_ID_MID_SKUID = Indexes0.SELLER_FETCH_ORDER_ID_MID_SKUID;
    public static final Index SELLER_FETCH_ORDER_IDX_BILLID = Indexes0.SELLER_FETCH_ORDER_IDX_BILLID;
    public static final Index SELLER_FETCH_ORDER_IDX_MID_CITYID_MKTID_FLID_SKUID = Indexes0.SELLER_FETCH_ORDER_IDX_MID_CITYID_MKTID_FLID_SKUID;
    public static final Index SELLER_FETCH_ORDER_IDX_MID_OID = Indexes0.SELLER_FETCH_ORDER_IDX_MID_OID;
    public static final Index SELLER_FETCH_ORDER_IDX_PLTF_BARCODE = Indexes0.SELLER_FETCH_ORDER_IDX_PLTF_BARCODE;
    public static final Index SELLER_FETCH_ORDER_PRIMARY = Indexes0.SELLER_FETCH_ORDER_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index BASE_BUSINESS_INFO_PRIMARY = Internal.createIndex("PRIMARY", BaseBusinessInfo.BASE_BUSINESS_INFO, new OrderField[] { BaseBusinessInfo.BASE_BUSINESS_INFO.ID }, true);
        public static Index BASE_BUSINESS_INFO_UK_BIZ_CODE = Internal.createIndex("uk_biz_code", BaseBusinessInfo.BASE_BUSINESS_INFO, new OrderField[] { BaseBusinessInfo.BASE_BUSINESS_INFO.CITY_CODE, BaseBusinessInfo.BASE_BUSINESS_INFO.MARKET_CODE, BaseBusinessInfo.BASE_BUSINESS_INFO.FLOOR_CODE, BaseBusinessInfo.BASE_BUSINESS_INFO.BUSINESS_CODE }, false);
        public static Index PLATFORM_SKU_IDX_BIZFULLNAME_SPUGOODSNO = Internal.createIndex("idx_bizfullname_spugoodsno", PlatformSku.PLATFORM_SKU, new OrderField[] { PlatformSku.PLATFORM_SKU.BIZ_FULL_NAME, PlatformSku.PLATFORM_SKU.SPU_GOODS_NO }, false);
        public static Index PLATFORM_SKU_IDX_BIZID_SPUGOODSNO = Internal.createIndex("idx_bizid_spugoodsno", PlatformSku.PLATFORM_SKU, new OrderField[] { PlatformSku.PLATFORM_SKU.BIZ_ID, PlatformSku.PLATFORM_SKU.SPU_GOODS_NO }, false);
        public static Index PLATFORM_SKU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID = Internal.createIndex("idx_cityid_mktid_flrcode_spugoodsno_bizid", PlatformSku.PLATFORM_SKU, new OrderField[] { PlatformSku.PLATFORM_SKU.CITY_ID, PlatformSku.PLATFORM_SKU.MARKET_ID, PlatformSku.PLATFORM_SKU.FLOOR_CODE, PlatformSku.PLATFORM_SKU.SPU_GOODS_NO }, false);
        public static Index PLATFORM_SKU_IDX_SPUID = Internal.createIndex("idx_spuid", PlatformSku.PLATFORM_SKU, new OrderField[] { PlatformSku.PLATFORM_SKU.SPU_ID }, false);
        public static Index PLATFORM_SKU_PRIMARY = Internal.createIndex("PRIMARY", PlatformSku.PLATFORM_SKU, new OrderField[] { PlatformSku.PLATFORM_SKU.ID }, true);
        public static Index PLATFORM_SPU_IDX_BIZID_SPUGOODSNO = Internal.createIndex("idx_bizid_spugoodsno", PlatformSpu.PLATFORM_SPU, new OrderField[] { PlatformSpu.PLATFORM_SPU.BIZ_ID, PlatformSpu.PLATFORM_SPU.SPU_GOODS_NO }, false);
        public static Index PLATFORM_SPU_IDX_CITYID_MKTID_FLRCODE_SPUGOODSNO_BIZID = Internal.createIndex("idx_cityid_mktid_flrcode_spugoodsno_bizid", PlatformSpu.PLATFORM_SPU, new OrderField[] { PlatformSpu.PLATFORM_SPU.CITY_ID, PlatformSpu.PLATFORM_SPU.MARKET_ID, PlatformSpu.PLATFORM_SPU.FLOOR_CODE, PlatformSpu.PLATFORM_SPU.SPU_GOODS_NO, PlatformSpu.PLATFORM_SPU.BIZ_ID }, false);
        public static Index PLATFORM_SPU_PRIMARY = Internal.createIndex("PRIMARY", PlatformSpu.PLATFORM_SPU, new OrderField[] { PlatformSpu.PLATFORM_SPU.ID }, true);
        public static Index SELLER_PLATFORM_CODE = Internal.createIndex("platform_code", Seller.SELLER, new OrderField[] { Seller.SELLER.PLATFORM_CODE, Seller.SELLER.PLATFORM_IDENTITY }, true);
        public static Index SELLER_PRIMARY = Internal.createIndex("PRIMARY", Seller.SELLER, new OrderField[] { Seller.SELLER.ID }, true);
        public static Index SELLER_SHORT_NAME = Internal.createIndex("short_name", Seller.SELLER, new OrderField[] { Seller.SELLER.SHORT_NAME }, true);
        public static Index SELLER_FETCH_ORDER_ID_MID_SKUID = Internal.createIndex("id_mid_skuId", SellerFetchOrder.SELLER_FETCH_ORDER, new OrderField[] { SellerFetchOrder.SELLER_FETCH_ORDER.MERCHANT_ID, SellerFetchOrder.SELLER_FETCH_ORDER.PLATFORM_SPU_ID }, false);
        public static Index SELLER_FETCH_ORDER_IDX_BILLID = Internal.createIndex("idx_billid", SellerFetchOrder.SELLER_FETCH_ORDER, new OrderField[] { SellerFetchOrder.SELLER_FETCH_ORDER.BILL_ID }, false);
        public static Index SELLER_FETCH_ORDER_IDX_MID_CITYID_MKTID_FLID_SKUID = Internal.createIndex("idx_mid_cityid_mktid_flid_skuid", SellerFetchOrder.SELLER_FETCH_ORDER, new OrderField[] { SellerFetchOrder.SELLER_FETCH_ORDER.MERCHANT_ID, SellerFetchOrder.SELLER_FETCH_ORDER.CITY_ID, SellerFetchOrder.SELLER_FETCH_ORDER.MARKET_ID, SellerFetchOrder.SELLER_FETCH_ORDER.FLOOR_CODE, SellerFetchOrder.SELLER_FETCH_ORDER.PLATFORM_SKU_NAME }, false);
        public static Index SELLER_FETCH_ORDER_IDX_MID_OID = Internal.createIndex("idx_mid_oid", SellerFetchOrder.SELLER_FETCH_ORDER, new OrderField[] { SellerFetchOrder.SELLER_FETCH_ORDER.MERCHANT_ID, SellerFetchOrder.SELLER_FETCH_ORDER.SELLER_ORDER_ID }, false);
        public static Index SELLER_FETCH_ORDER_IDX_PLTF_BARCODE = Internal.createIndex("idx_pltf_barcode", SellerFetchOrder.SELLER_FETCH_ORDER, new OrderField[] { SellerFetchOrder.SELLER_FETCH_ORDER.PLATFORM_BARCODE }, false);
        public static Index SELLER_FETCH_ORDER_PRIMARY = Internal.createIndex("PRIMARY", SellerFetchOrder.SELLER_FETCH_ORDER, new OrderField[] { SellerFetchOrder.SELLER_FETCH_ORDER.ID }, true);
    }
}
