/*
 * This file is generated by jOOQ.
 */
package com.huice.service_dyna.db;


import com.huice.service_dyna.db.tables.BaseBusinessInfo;
import com.huice.service_dyna.db.tables.PlatformSku;
import com.huice.service_dyna.db.tables.PlatformSpu;
import com.huice.service_dyna.db.tables.Seller;
import com.huice.service_dyna.db.tables.SellerFetchOrder;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in fdk_forwarder2
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 代拿市场档口商户信息表
     */
    public static final BaseBusinessInfo BASE_BUSINESS_INFO = BaseBusinessInfo.BASE_BUSINESS_INFO;

    /**
     * 系统规格|郑保乐|2021-06-08
     */
    public static final PlatformSku PLATFORM_SKU = PlatformSku.PLATFORM_SKU;

    /**
     * 系统货品|郑保乐|2021-06-08
     */
    public static final PlatformSpu PLATFORM_SPU = PlatformSpu.PLATFORM_SPU;

    /**
     * 销售商表
     */
    public static final Seller SELLER = Seller.SELLER;

    /**
     * 代拿子单，对应销端小标签|郑保乐|2021-06-08
     */
    public static final SellerFetchOrder SELLER_FETCH_ORDER = SellerFetchOrder.SELLER_FETCH_ORDER;
}
